---
title: The Open Research Movement
author:
    - Dr Danna Gifford, Unit coordinator (2023), danna.gifford@manchester.ac.uk
date: ""
output: 
 html_document:
  theme: flatly
  toc: true
  toc_float: true
---
# Introduction

The Open Research movement is a global initiative that seeks to revolutionize the way research is conducted, shared, and accessed. It is driven by a set of core principles that emphasize openness, transparency, and collaboration throughout the research process. In this workshop, we will delve into the key aspects and benefits of the Open Research movement.

# Key Principles of Open Research

## Open Access

Open Access is a cornerstone of the Open Research movement. It advocates for the unrestricted availability of research publications, data, and findings to the public. Researchers and institutions are encouraged to make their work freely accessible, either through open-access journals, preprint servers, or institutional repositories. Open Access promotes the democratization of knowledge by removing financial barriers to access, enabling anyone with an internet connection to benefit from research findings.

Organizations like the [Open Access Scholarly Publishers Association (OASPA)](https://oaspa.org/) and [Directory of Open Access Journals (DOAJ)](https://doaj.org/) are at the forefront of advocating for and ensuring the quality and integrity of open-access journals. They work diligently to establish best practices and standards in open-access publishing. Additionally, institutions and funders play a significant role in advancing open access. Bodies such as the [Open Research Funders Group (ORFG)](https://www.orfg.org/) and [Plan S](https://www.coalition-s.org/) are driving initiatives to make research outputs openly accessible, thereby democratizing knowledge and fostering innovation.

## Open Data

Open Data is the practice of openly sharing research data, allowing others in the scientific community and beyond to access, scrutinize, and build upon it. Researchers are encouraged to provide well-documented datasets alongside their publications. This openness not only enhances the reproducibility of research but also fosters innovation, as diverse perspectives can be applied to existing datasets to answer new questions or explore new hypotheses.

Several platforms serve as excellent places for sharing open data, with [Figshare](https://figshare.com/) being a prominent example. Figshare provides researchers with a user-friendly, web-based repository where they can effortlessly upload, manage, and share their datasets. Its versatility extends beyond data storage, as it accommodates a wide range of research outputs, including figures, code, presentations, and more. Researchers benefit from Figshare's commitment to open access, as it facilitates the seamless dissemination of data to the global scientific community. Moreover, Figshare offers tools for data citation, ensuring proper attribution and recognition for data creators. Beyond Figshare, other notable platforms like [Zenodo](https://zenodo.org/), [Dataverse](https://dataverse.org/), and [Dryad](https://datadryad.org/) also contribute significantly to the open data landscape, collectively fostering a culture of data sharing and accessibility that accelerates scientific discovery and innovation.

In genomics research, sharing data is pivotal, and two prominent databases, [NCBI](https://www.ncbi.nlm.nih.gov/) and [ENA](https://www.ebi.ac.uk/ena), facilitate this practice. NCBI's GenBank and ENA store diverse genomic data, fostering global collaboration and data transparency. Researchers worldwide access, analyze, and contribute to these databases, advancing scientific understanding of genetics. Sharing data played a critical role during the COVID-19 crisis, enabling rapid global collaboration among scientists, researchers, and healthcare professionals to better understand the virus, track its spread, and develop effective interventions and vaccines.  

Read [Intelligent open science: viral genomic data sharing during the COVID-19 pandemic](intelligent-open-science.pdf), a case study commissioned by the GOV.UK, to learn more.


## Open Collaboration

Open Collaboration is a fundamental tenet of the Open Research movement. It encourages researchers to collaborate across disciplines, institutions, and geographical boundaries. By breaking down silos and fostering interdisciplinary teamwork, Open Collaboration can lead to more comprehensive and innovative research outcomes. Initiatives such as open-source software development and collaborative research platforms play a crucial role in facilitating these collaborations.

Initiatives such as and [Collaborative Open Innovation Network (CoINs)](https://en.wikipedia.org/wiki/Collaborative_innovation_network) are dedicated to promoting Open Collaboration. These organizations provide platforms, resources, and networks that facilitate knowledge sharing and collaborative efforts, bridging gaps in research and accelerating progress in diverse fields. Read the following article to learn more:  

Levine, Sheen S. and Michael J. Prietula. (2013) [Open Collaboration for Innovation: Principles and Performance](https://pubsonline.informs.org/doi/10.1287/orsc.2013.0872) Organization Science.

# Advantages of Open Research

## Reproducibility

One of the central advantages of Open Research is reproducibility. By making research methods, data, and code openly available, researchers can ensure that their work is transparent and accessible. This transparency allows other researchers to validate and reproduce findings, enhancing the credibility and reliability of scientific research. Reproducibility is essential for building a solid foundation of knowledge upon which future research can be built.

## Innovation

Innovation thrives in the open research environment. Openly accessible data, findings, and collaborative opportunities enable researchers to leverage existing work to drive new discoveries and advancements. The ability to build upon the work of others accelerates the pace of innovation and can lead to breakthroughs in various fields, from medicine to technology.

## Accessibility

Open Research promotes accessibility by making research outputs available to a broader audience, including individuals outside the academic community. This accessibility has the potential to bridge the gap between academic research and practical applications in the real world. Policymakers, educators, and the general public can benefit from access to research findings, leading to evidence-based decision-making and societal progress.

# Challenges and Future Directions

While the Open Research movement has made significant progress, it faces several challenges on its path to widespread adoption. These challenges include securing sustainable funding for open-access publishing, addressing data privacy concerns, and fostering cultural shifts within academia that prioritize openness and collaboration.

However, the future of Open Research looks promising. More funding agencies, institutions, and individual researchers are embracing its principles. Initiatives to develop open research infrastructure and support open science practices are gaining momentum, indicating a positive trajectory for the movement.

# Open Research at The University of Manchester

The University of Manchester is an active participant in the Open Research Movement, demonstrating a strong commitment to openness, transparency, and collaboration in research practices. The University has embraced Open Access publishing, making a significant portion of its research output freely available to the public, thereby increasing the accessibility of knowledge. Moreover, it actively encourages researchers to share their datasets openly, promoting the principles of Open Data. The University also fosters interdisciplinary collaborations and provides support for researchers to engage in open science initiatives, thus contributing to the ethos of Open Collaboration. By championing these principles and actively participating in the Open Research Movement, the University is not only advancing the credibility and reproducibility of research but also fostering a culture of innovation and knowledge sharing within its academic community and beyond.

Listen to Professor Collette Fagan speak about The University of Manchester's committment to Open Research and read about the University's [Position Statement on Open Research](https://www.openresearch.manchester.ac.uk/about-us/position-statement/). You can also explore [Support offered by the University](https://www.openresearch.manchester.ac.uk/support/) for conducting Open Research:  
<iframe width="560" height="315" src="https://www.youtube.com/embed/aWOb9KHaQv0?si=mmur-LDtIXQUQxmJ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

## The Office for Open Research
Led by the Library, the [Office for Open Research](https://www.openresearch.manchester.ac.uk/) supports the University's aims to create a more open and responsible research environment. It represents one of the most substantial investments in the future of publishing, data, and open knowledge ever made by a UK university. The establishment of the Open Research Service Partnership is part of a coordinated effort to respond to the Open Research agenda, further bolstering the support available to researchers and expediting the adoption of Open Research practices. The creation of this office establishes a central hub for Open Research initiatives at The University of Manchester, positioning the institution at the forefront of this global movement. Fostering open dialogue with the research community is a priority, allowing for the clear delineation of Open Research goals and the accommodation of the diverse needs of various research communities.

Watch this video to learn more about the initiatives undertaken by the University:  
<iframe width="560" height="315" src="https://www.youtube.com/embed/78nbIrgS2LY?si=9t2wUHMFMyPbaHCr" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>


